source "https://rubygems.org"

gem "jekyll", "~> 4.1"
gem "jekyll-sitemap", "~> 1.4.0"
gem "jekyll-mentions", "~> 1.6.0"
gem "jekyll-paginate", "~> 1.1.0"
gem "jekyll-seo-tag", "~> 2.6.1"
gem "jekyll-redirect-from", "~> 0.16"
gem "jekyll-default-layout", "~> 0.1"
gem "jekyll-feed", "~> 0.15"
gem "jemoji", "~> 0.12"
gem "jekyll-remote-theme", "~> 0.3"
gem "kramdown-parser-gfm", "~> 1.1.0"
gem "webrick", "~> 1.7"
